namespace:
  name: staging
 
image:
  repository: nginx 
  tag: 1.18.0

resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "50m"

replicaCount: 1


service:
  type: ClusterIP
  port: 8111

configmap:
  version: 1.18.0 
