namespace:
  name: demo 
 
image:
  repository: nginx 
  tag: apline
  pullPolicy: IfNotPresent

resources:
      requests:
        memory: "256Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "50m"

replicaCount: 3


service:
  type: ClusterIP
  port: 8111

configmap:
  version: alpine
