apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sadek
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: solutions/helm/nginx-sadek
    repoURL: https://github.com/Zak4sad/nd064_course_1 
    targetRevision: HEAD
