apiVersion: v1
kind: Service
metadata:
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
      protocol: TCP
